export const INQUIRY_LOADING= "INQUIRY_LOADING";
export const GET_INQUIRIES= "GET_INQUIRIES";
export const INQUIRY_FAILURE= "INQUIRY_FAILURE";
export const DELETE_INQUIRY= "DELETE_INQUIRY";
export const TOGGLE_STATUS= "TOGGLE_STATUS";

